export const FETCH_WEATHER = "FETCH_WEATHER";
export const GET_CACHED_WEATHER = "GET_CACHED_WEATHER";
export const CLEAR_WEATHER = "CLEAR_WEATHER";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const GET_CACHED_WEATHER_WITH_ERROR = "GET_CACHED_WEATHER_WITH_ERROR";